# Usamos la imagen oficial de PostGIS como base
FROM postgis/postgis:15-3.3

# Instalamos GDAL y otros paquetes necesarios
RUN apt-get update && apt-get install -y \
    gdal-bin \
    && rm -rf /var/lib/apt/lists/*

# Copiamos los scripts de inicialización
COPY ./init_postgres.sql /docker-entrypoint-initdb.d/
COPY ./insertar_puntos.sh /docker-entrypoint-initdb.d/
COPY ./merenderos.kml /data/merenderos.kml

